import { PostItem, QueueItem, CourseImpactItem, UserProfile, Community, CircularNoticeItem, CommentItem, CampusPulseItem } from '@/types';

/**
 * Explicit demo mode flag.
 * All sample posts, mock notices, and fallback data are clearly labeled as DEMO content.
 */
export const DEMO_MODE = true;
export const DEMO_DATASET_LABEL = 'Campus Sandbox / Demo Dataset';

export const CAMPUS_PULSE_ITEMS: CampusPulseItem[] = [
  {
    id: 'pulse-notice-1',
    type: 'notice',
    title: 'End-Semester Examination Schedule',
    metadata: 'Examination Cell · Published recently',
    summary: 'Timetable clash resolution portal closes this Friday at 23:59.',
    actionLabel: 'View Notice',
    targetView: 'notices',
    targetData: 'circular_endsem_schedule_latest.pdf',
    tagText: 'Official Notice',
  },
  {
    id: 'pulse-event-1',
    type: 'event',
    title: 'Autonomous Robotics & ROS2 Workshop',
    metadata: 'Tomorrow · Makerspace Lab 402',
    summary: 'Hands-on Nav2 stack demo. 32 of 40 seats reserved.',
    actionLabel: 'Reserve Seat',
    targetView: 'robotics-club',
    targetData: 'Autonomous Robotics & ROS2 Workshop',
    tagText: 'Campus Event',
  },
  {
    id: 'pulse-community-1',
    type: 'community',
    title: 'Hackathon Commons',
    metadata: 'Active today · 18 new discussions',
    summary: 'Intercollegiate hackathon team formations and project pitches.',
    actionLabel: 'Open Space',
    targetView: 'communities',
    targetData: 'hackathon_teams',
    tagText: 'Community',
  },
];

export const INITIAL_USER: UserProfile = {
  id: '',
  username: 'Guest',
  handle: 'u/guest',
  email: '',
  avatarUrl: '',
  karma: '0',
  role: 'Guest',
  department: 'Campus Member',
  rollNumber: '',
  isLoggedIn: false,
  createdAt: new Date().toISOString(),
};

export const DEMO_COMMUNITIES: Community[] = [
  {
    id: 'comm-1',
    name: 'Robotics Club',
    slug: 'robotics-club',
    prefix: '',
    title: 'Robotics & Automation Society',
    description: 'Hardware prototyping, ROS 2 navigation, autonomous rovers, and combat robotics.',
    memberCount: 1420,
    category: 'club',
    tier: 'Student Club',
    iconBg: 'bg-[#FF4500]',
    createdAt: '2024-08-01T00:00:00.000Z',
  },
  {
    id: 'comm-2',
    name: 'Examination Cell',
    slug: 'examination_cell',
    prefix: '',
    title: 'Controller of Examinations',
    description: 'Official timetables, hall ticket releases, and semester examination directives.',
    memberCount: 4280,
    category: 'official',
    tier: 'Institutional Office',
    iconBg: 'bg-blue-600',
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'comm-3',
    name: 'Career & Placements',
    slug: 'placement_office',
    prefix: '',
    title: 'Career Development Centre',
    description: 'Campus placement drives, company interview schedules, and shortlists.',
    memberCount: 3890,
    category: 'official',
    tier: 'Institutional Office',
    iconBg: 'bg-emerald-600',
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'comm-4',
    name: 'Academic Affairs',
    slug: 'dean_academics',
    prefix: '',
    title: 'Dean of Academic Affairs',
    description: 'Curriculum directives, academic policies, and research fellowships.',
    memberCount: 4120,
    category: 'academic',
    tier: 'Institutional Office',
    iconBg: 'bg-purple-600',
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'comm-5',
    name: 'Hackathon Commons',
    slug: 'hackathon_teams',
    prefix: '',
    title: 'Hackathon Commons',
    description: 'Find team members for National Hackathons, ICPC, and collegiate hackathons.',
    memberCount: 890,
    category: 'commons',
    tier: 'Student Commons',
    iconBg: 'bg-amber-600',
    createdAt: '2024-09-01T00:00:00.000Z',
  },
  {
    id: 'comm-6',
    name: 'Campus Commons',
    slug: 'campus_general',
    prefix: '',
    title: 'General Campus Commons',
    description: 'Everyday campus discussions, lost & found, and student life updates.',
    memberCount: 3100,
    category: 'commons',
    tier: 'Student Commons',
    iconBg: 'bg-slate-600',
    createdAt: '2024-01-01T00:00:00.000Z',
  },
];

export const DEMO_COMMENTS: Record<string, CommentItem[]> = {
  'all-1': [
    {
      id: 'comm-101',
      postId: 'all-1',
      author: 'Rahul Verma',
      content: 'Is there any clash form open for CS201 and EC304 yet?',
      timestamp: '4 hours ago',
      createdAt: '2025-04-20T08:00:00.000Z',
      upvotes: 12,
    },
    {
      id: 'comm-102',
      postId: 'all-1',
      author: 'Dr. V. Ramanathan',
      authorRole: 'COE Staff',
      content: 'The clash portal closes this Friday at 23:59. Please log clash course IDs directly through the SIS link.',
      timestamp: '2 hours ago',
      createdAt: '2025-04-20T10:00:00.000Z',
      upvotes: 28,
    },
  ],
  'rob-1': [
    {
      id: 'comm-201',
      postId: 'rob-1',
      author: 'Tanmay Deshmukh',
      content: 'Can our competition team reserve the CNC mill for Saturday 10 AM to 2 PM?',
      timestamp: '1 hour ago',
      createdAt: '2025-04-20T09:30:00.000Z',
      upvotes: 8,
    },
  ],
};

export const ROBOTICS_POSTS: PostItem[] = [
  {
    id: 'rob-1',
    community: 'Robotics Club',
    communityPrefix: '',
    communityIconBg: 'bg-[#FF4500]',
    author: 'Dr. Ramanathan',
    authorRole: 'Faculty Advisor',
    authorBadge: 'Faculty Advisor',
    authorBadgeType: 'mod',
    timestamp: '2 hours ago',
    pinned: true,
    pinnedLabel: 'PINNED NOTICE',
    title: 'Lab Access Protocol for Finals Preparation & Competition Slots [MANDATORY READ]',
    content: 'Effective Monday, 24-hour access to Lab 402 is activated for verified project squads. All soldering stations and the precision CNC mill require prior calendar checkout. Unattended 3D print operations must display safety tags with emergency kill-switch signoffs.',
    upvotes: 342,
    commentsCount: 48,
    attachment: {
      type: 'pdf',
      fileName: 'Lab_Access_SafetyDirectives_v2.pdf',
      metaText: 'PDF Document • 1.84 MB • Signed by Faculty Chair',
      verifiedLabel: 'Faculty Authenticated (Tier 1)',
    },
  },
  {
    id: 'rob-2',
    community: 'Robotics Club',
    communityPrefix: '',
    author: 'Tanmay Deshmukh',
    authorRole: 'Tech Lead',
    authorBadge: 'Tech Lead',
    authorBadgeType: 'tech',
    timestamp: '4 hours ago',
    title: 'Autonomous Rover Field Test Results & Telemetry Log #04',
    content: 'Completed 4.2 km outdoor navigation trial on the campus South Grounds. RTK-GPS localization drift was under 3.2cm. SLAM lidar points were streamed in real-time over 5.8GHz point-to-point link with zero packet drops.',
    flairs: [
      { label: 'Hardware', bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
      { label: 'ROS2', bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200' },
    ],
    upvotes: 156,
    commentsCount: 28,
    attachment: {
      type: 'image',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCoQSfwwv7HXkOvLpv7LBiDBTTA_GTEASarWilTWJNRf6mmcg3HBDaQlaXomEQ5BsDeZeUJpdfwCq-uVK8eyPdbfOxGf7WMXBBWVEMT46C2ZjsP-OtJ0duc5GU1HL4bZbdBlTz1x2Q8aVTp47n6DqBzBpPjeuyPNEBTYMKHAVrip1_dtFe5mlTAVv_igm23vE1Suh1Cp_pOBXgAWpNalQbu93gn3K1ek7iBvmxpDd5XrjkhU2WlAEoM',
      imageAlt: 'Field test rover on rugged campus terrain',
    },
  },
  {
    id: 'rob-3',
    community: 'Robotics Club',
    communityPrefix: '',
    author: 'Kavya Rao',
    authorRole: 'Kinematics Lead',
    authorBadge: 'Kinematics Lead',
    authorBadgeType: 'tech',
    timestamp: '5 hours ago',
    title: 'Project Cerberus: 12-DoF Quadruped Trotting Gait & MPC Stair Climb Validation',
    content: 'After tuning our Convex Model Predictive Controller (MPC) at 250Hz on the Teensy 4.1 companion board, Cerberus successfully negotiated the 14-step concrete staircase outside Lab 402 with no manual intervention! Foot force sensor data matches our MuJoCo simulation within 4.8% error margin.',
    flairs: [
      { label: 'Showcase', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
      { label: 'Simulation', bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200' },
    ],
    upvotes: 218,
    commentsCount: 37,
    attachment: {
      type: 'telemetry',
      metaText: 'Leg Actuator Telemetry: 12x Brushless Planetary Actuators (35Nm peak torque)',
      verifiedLabel: 'FW v2.4.1',
    },
  },
  {
    id: 'rob-4',
    community: 'Robotics Club',
    communityPrefix: '',
    author: 'Robotics Committee',
    authorRole: 'Official Committee',
    authorBadge: 'Official Committee',
    authorBadgeType: 'official',
    timestamp: 'Yesterday',
    title: 'Workshop: ROS2 Navigation Stack (Nav2) on Jetson Nano',
    content: 'Prerequisites: Basic Linux CLI knowledge and Python 3 familiarity. We will cover sensor fusion with EKF, costmap generation, and deploying an autonomous path planner to our physical robot platforms.',
    flairs: [
      { label: 'Workshop', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
    ],
    upvotes: 94,
    commentsCount: 14,
    attachment: {
      type: 'workshop',
      workshopDate: { month: 'OCT', day: '19' },
      workshopTime: 'Saturday · 10:00 AM – 1:30 PM',
      workshopLocation: 'Location: Makerspace Lab 402 • Hardware kits provided',
      workshopSeats: { total: 40, filled: 32 },
    },
  },
  {
    id: 'rob-5',
    community: 'Robotics Club',
    communityPrefix: '',
    author: 'Rohan Iyer',
    authorRole: 'DAQ Lead',
    authorBadge: 'DAQ Systems',
    authorBadgeType: 'tech',
    timestamp: '8 hours ago',
    title: 'Formula Electric DAQ Overhaul: Dual CAN-FD Buses + Live InfluxDB & Grafana Telemetry',
    content: 'We just bench-tested the Mk.IV battery management system (BMS) and inverter datalogger. Operating at 2Mbps on the primary drivetrain bus with over 64 sensor channels sampled at 100Hz. In-pit laptop receives telemetry wirelessly with latency under 12ms.',
    flairs: [
      { label: 'Electronics', bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
      { label: 'Telemetry', bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200' },
    ],
    upvotes: 184,
    commentsCount: 19,
    attachment: {
      type: 'telemetry',
      telemetryStats: [
        { label: 'Peak CAN Load', val: '41% @ 100Hz' },
        { label: 'Telemetry Link', val: 'ESP32 Wi-Fi AP + UDP Bridge' },
      ],
    },
  },
  {
    id: 'rob-6',
    community: 'Robotics Club',
    communityPrefix: '',
    author: 'Priya Sharma',
    authorRole: 'Fab Lab Coordinator',
    authorBadge: 'Fab Lab Coordinator',
    authorBadgeType: 'tech',
    timestamp: '11 hours ago',
    title: 'Lab 402 Guide: Printing 95A TPU Gripper Fingers without Clogging Direct-Drives',
    content: 'Reminder for everyone fabricating soft-robotics pneumatic pads: Please dry the TPU filament in our vacuum oven for 4 hours at 55°C before running. Loosen the extruder idler tension screw by 2.5 full rotations to prevent filament buckle. Our pre-configured slicer profiles are now saved on the Lab Desktop.',
    flairs: [
      { label: 'Lab Guide', bg: 'bg-amber-50', text: 'text-amber-800', border: 'border-amber-200' },
    ],
    upvotes: 112,
    commentsCount: 22,
  },
  {
    id: 'rob-7',
    community: 'Robotics Club',
    communityPrefix: '',
    author: 'Vikram Seth',
    authorRole: 'UAV Flight Lead',
    timestamp: '14 hours ago',
    title: 'Autonomous Hexacopter Precision Landing on Moving Platform using Apriltag Visual Servoing',
    content: "Video footage and logs from yesterday's sports field trials: Using an Oak-D Pro stereo camera running onboard pose estimation via OpenCV and MAVROS. Touchdown RMS error on a moving target cart traveling at 1.5 m/s was 4.1 cm!",
    flairs: [
      { label: 'Computer Vision', bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
      { label: 'UAV Flight', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
    ],
    upvotes: 143,
    commentsCount: 31,
  },
  {
    id: 'rob-8',
    community: 'Robotics Club',
    communityPrefix: '',
    author: 'Siddharth K.',
    authorRole: 'Hardware Dev',
    timestamp: '16 hours ago',
    title: 'Component sharing: Anyone have an extra STM32F401 board for the weekend?',
    content: 'Our inverted pendulum motor controller MCU fried during PWM tuning today. Need a spare Nucleo or BlackPill STM32F401 board until Monday shipment arrives. Can exchange with a Teensy 4.0 or brand new IMU modules as collateral!',
    flairs: [
      { label: 'Equipment Borrow', bg: 'bg-amber-50', text: 'text-amber-800', border: 'border-amber-200' },
    ],
    upvotes: 18,
    commentsCount: 8,
    attachment: {
      type: 'hardware',
      metaText: '8 Comments (2 members offered board: Nikhil & Tanmay)',
    },
  },
  {
    id: 'rob-9',
    community: 'Robotics Club',
    communityPrefix: '',
    author: 'Arjun Nair',
    authorRole: "Robotics Alumni",
    authorBadge: "Robotics Alumni",
    authorBadgeType: 'alumni',
    timestamp: 'Yesterday',
    title: 'Tips for Robotics R&D Internships: Portfolio, ROS2 C++ nodes, and Hardware git repos',
    content: 'Currently working at a warehouse autonomous mobile robot (AMR) company in Bengaluru. When hiring interns, we look for clean C++17/20, familiarity with ROS2 lifecycle nodes, URDF design in Fusion360/Onshape, and demonstrable git commits rather than classroom textbook grades. Happy to do resume reviews in Lab 402 this Saturday afternoon.',
    flairs: [
      { label: 'Career & Research', bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200' },
    ],
    upvotes: 89,
    commentsCount: 41,
  },
];

export const ALL_CAMPUS_POSTS: PostItem[] = [
  {
    id: 'all-1',
    community: 'Examination Cell',
    communityPrefix: '',
    author: 'Dr. V. Ramanathan',
    timestamp: '6 hours ago',
    pinned: true,
    pinnedLabel: 'OFFICIAL NOTICE',
    categoryTier: 'TIER 1 · INSTITUTIONAL',
    docCode: 'CIR/EX-88',
    title: 'End-Semester Examination Schedule — Comprehensive Timetable & Clash Directives',
    content: 'Issued under the authority of Controller of Examinations for all B.Tech, M.Tech, and Dual-Degree cohorts. Please inspect shifts and hall allocations thoroughly.',
    upvotes: 1200,
    commentsCount: 148,
    attachment: {
      type: 'pdf',
      fileName: 'circular_endsem_schedule_latest.pdf',
      fileSize: '2.4 MB (14 Pages)',
      metaText: 'Executive Summary: Clash Portal closes this Friday at 23:59. Hall tickets now available. Non-programmable calculators only.',
      verifiedLabel: 'Deanery Signature Verified',
    },
  },
  {
    id: 'all-2',
    community: 'Career & Placements',
    communityPrefix: '',
    author: 'Career Development Centre',
    timestamp: '2 hours ago',
    categoryTier: 'TIER 1 · RECRUITMENT',
    title: 'Google, Microsoft, and Texas Instruments Campus Recruitment Drives: Final Shortlist & Interview Slots',
    content: 'Interviews are slated for this Wednesday to Friday in Main Academic Block IV. Students listed must complete slot locking in CDC portal by 20:00 today. Formal attire and 3 stamped physical resumes strictly required.',
    upvotes: 384,
    commentsCount: 62,
    attachment: {
      type: 'excel',
      fileName: 'Cohort_Final_Interview_Slots_v3.xlsx',
      fileSize: '512 KB',
      metaText: 'Authenticated CDC Signoff • 2,940 views',
    },
  },
  {
    id: 'all-3',
    community: 'Robotics Club',
    communityPrefix: '',
    author: 'Robotics & Automation Society',
    timestamp: '4 hours ago',
    categoryTier: 'TIER 2 · CLUB EVENT',
    title: 'Registrations Open: RoboWars Annual Collegiate Battle Arena!',
    content: '15kg & 30kg combat robot classes. ₹1.5L prize pool with hardware sponsorship from Texas Instruments. Matches take place at Central Indoor Arena this weekend.',
    upvotes: 218,
    commentsCount: 45,
    attachment: {
      type: 'event',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAxNdwMFan_uzFSqhT9Ot6tt-ydGts4IHU3c_loq0DR5gvoh4CqgjWPeQZ8GzEtCUjW_3N0mbh_mzT7oe8Qvgag5U579vABtC1LUyXCY3lAFjSgJCxinfGx9NUwH7nbfR0sHwhjBrMVXzWpRpISDJvY0D3bbt1V7Jas2tHLa2Fnl7T6E1p5Wi7l_yIoRr--zWJqEwI1UU-qmWIm7hVt8QwHbks0VDw6yxSXvt00YMy_CVK4ux4e2WS6',
      imageAlt: 'Combat robot tournament arena',
      workshopDate: { month: 'JAN', day: '14' },
      workshopTime: 'This Weekend • Central Indoor Arena (SAC Complex)',
      workshopSeats: { total: 20, filled: 12 },
    },
  },
  {
    id: 'all-4',
    community: 'Hackathon Commons',
    communityPrefix: '',
    author: 'Rohan Mehta',
    timestamp: '5 hours ago',
    categoryTier: 'TIER 3 · COMMONS',
    title: '[National Hackathon Qualifier] Looking for 1 Frontend Dev & 1 ML Engineer!',
    content: 'We are building an offline-first Edge AI diagnostic pipeline for agrarian pest detection. Prototype already runs on Jetson Nano. Need strong team members for UI integration and model quantization before Thursday review.',
    flairs: [
      { label: '#Hackathon', bg: 'bg-[#EDEFF1]', text: 'text-[#1A1A1B]' },
      { label: '#EdgeAI', bg: 'bg-[#EDEFF1]', text: 'text-[#1A1A1B]' },
      { label: '#NextJS', bg: 'bg-[#EDEFF1]', text: 'text-[#1A1A1B]' },
    ],
    upvotes: 74,
    commentsCount: 19,
  },
  {
    id: 'all-5',
    community: 'Academic Affairs',
    communityPrefix: '',
    author: 'Prof. K. S. Ramanujam',
    timestamp: '6 hours ago',
    categoryTier: 'TIER 1 · SPONSORED RESEARCH',
    title: 'Call for Undergraduate & Postgraduate Research Fellows: Quantum Cryptography & Key Exchange',
    content: 'DST-SERB sponsored project looking for 2 student researchers proficient in C++20, OpenSSL 3.x internals, and Lattice Cryptography. Monthly stipend of ₹28,000 provided with co-authorship for upcoming IEEE S&P submission. Candidates with GPA > 8.5 preferred.',
    flairs: [
      { label: '₹28k/mo Stipend', bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200' },
      { label: 'Deadline: Friday', bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
      { label: 'Lab 402, Block VI', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
    ],
    upvotes: 192,
    commentsCount: 38,
  },
  {
    id: 'all-6',
    community: 'Campus Commons',
    communityPrefix: '',
    author: 'Sahil Trivedi',
    timestamp: '7 hours ago',
    categoryTier: 'TIER 3 · COMMONS',
    flairs: [
      { label: 'LOST & FOUND', bg: 'bg-amber-100', text: 'text-amber-800' },
    ],
    title: '[FOUND] TI-84 Plus CE Graphing Calculator in Audi 3 during CS210 Lecture today',
    content: 'Found on row 8, seat 14 right after the morning 10:30 lecture. Has a custom blue matte case with a holographic Linux mascot sticker on the flip cover. Handed over to Academic Desk B Security Guard Room. Please show registration ID to claim.',
    upvotes: 143,
    commentsCount: 24,
  },
  {
    id: 'all-7',
    community: 'Hostel Affairs',
    communityPrefix: '',
    author: 'Chief Warden Office',
    timestamp: '8 hours ago',
    categoryTier: 'TIER 1 · CHIEF WARDEN NOTICE',
    flairs: [
      { label: 'CHIEF WARDEN NOTICE', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
    ],
    title: 'Hostel Curfew Extended to 01:00 AM for Examination Month; Night Canteen Operational Until 03:00 AM',
    content: 'Following representations from Student Council, turnstiles for Block A, B, C & D will remain open until 01:00 AM with biometric check-in. Central Night Canteen and Nescafe outlets at SAC will serve tea, coffee, and light meals until 03:00 AM throughout exam preparation weeks.',
    upvotes: 512,
    commentsCount: 89,
    attachment: {
      type: 'telemetry',
      metaText: 'Safety Notice: Security escorts will patrol between Central Library and Hostel Quad every 15 minutes between midnight and 04:00 AM.',
      verifiedLabel: 'Council Approved',
    },
  },
  {
    id: 'all-8',
    community: 'Student Mess Committee',
    communityPrefix: '',
    author: 'Mess Committee Secretary',
    timestamp: '9 hours ago',
    categoryTier: 'TIER 3 · CAMPUS POLL',
    flairs: [
      { label: 'CAMPUS POLL', bg: 'bg-purple-50', text: 'text-[#0079D3]', border: 'border-blue-200' },
    ],
    title: 'Vote on Caterer Menu Revision: North Mess vs South Mess Special Dinner options',
    content: 'Cast your vote before Thursday 6 PM. Results will directly determine the Wednesday Special menu for the upcoming month with the university catering contractor.',
    upvotes: 327,
    commentsCount: 71,
    attachment: {
      type: 'poll',
      pollTotalVotes: 1052,
      pollOptions: [
        { id: 'opt-1', text: 'Paneer Butter Masala + Garlic Naan + Gulab Jamun', votes: 612, percentage: 58 },
        { id: 'opt-2', text: 'Hyderabadi Dum Biryani + Mirchi Ka Salan + Double Ka Meetha', votes: 440, percentage: 42 },
      ],
    },
  },
  {
    id: 'all-9',
    community: 'IEEE Student Branch',
    communityPrefix: '',
    author: 'IEEE Student Branch',
    timestamp: '11 hours ago',
    categoryTier: 'TIER 2 · WORKSHOP',
    flairs: [
      { label: 'WORKSHOP', bg: 'bg-blue-100', text: 'text-blue-700' },
    ],
    title: 'Hands-on Bootcamp: Overleaf LaTeX for IEEE Transactions & Formatting Camera-Ready Manuscripts',
    content: 'Mastering BibTeX citations, vectorized vector graphics, TikZ circuit diagrams, and math formulas for major engineering conferences. Open to 3rd & 4th year B.Tech and PG students.',
    upvotes: 164,
    commentsCount: 31,
    attachment: {
      type: 'workshop',
      workshopDate: { month: 'NOV', day: '30' },
      workshopTime: 'Saturday · 14:00 IST',
      workshopLocation: 'CS Lab 2 & Online Stream',
      verifiedLabel: 'Free Certificate',
    },
  },
  {
    id: 'all-10',
    community: 'Campus Exchange',
    communityPrefix: '',
    author: 'Priya Menon',
    timestamp: '14 hours ago',
    categoryTier: 'TIER 3 · CAMPUS MARKET',
    title: '[Selling] Hercules 21-Speed Gear Bicycle + Core Textbooks (Sedra Smith, Oppenheim)',
    content: 'Cycle in good condition, newly replaced inner tubes and brake pads. Books have minimal pencil markings and include semester question paper bundles with answer keys. Selling cycle for ₹2,500 and book set for ₹800.',
    upvotes: 88,
    commentsCount: 16,
    attachment: {
      type: 'hardware',
      price: '₹2,500 (Bicycle) / ₹800 (Books)',
      metaText: 'Contact seller directly on campus chat or drop comment below.',
    },
  },
  {
    id: 'all-11',
    community: 'Sports Council',
    communityPrefix: '',
    author: 'Sports Council Secretary',
    timestamp: '16 hours ago',
    categoryTier: 'TIER 3 · TOURNAMENT',
    flairs: [
      { label: 'TOURNAMENT', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
    ],
    title: 'Inter-Hostel Football & Basketball Championship: Schedule of Semi-Finals & Final Match',
    content: 'Block B vs Block D football derby kicks off Friday at 18:00 on the Main Floodlit Stadium. Basketball finals take place at Indoor Stadium Saturday 19:30. Free admission with student ID cards.',
    upvotes: 245,
    commentsCount: 53,
    attachment: {
      type: 'telemetry',
      metaText: 'Stadium Passes Available at SAC Desk (Free with student ID)',
    },
  },
];

export const LAB_QUEUE_ITEMS: QueueItem[] = [
  {
    id: 'q-1',
    name: 'Bambu Lab X1-C #01',
    status: 'BUSY',
    statusClass: 'bg-amber-100 text-amber-800',
    progress: 68,
    fileName: 'Chassis_Mount_v4.stl',
    timeLeft: '1h 14m left',
  },
  {
    id: 'q-2',
    name: 'Prusa MK4 #02',
    status: 'AVAILABLE',
    statusClass: 'bg-emerald-100 text-emerald-800',
    details: 'Bed Temp: 23°C (Idle)',
    actionText: 'Submit G-Code →',
  },
  {
    id: 'q-3',
    name: 'Precision 3-Axis CNC',
    status: 'BOOKED',
    statusClass: 'bg-purple-50 text-purple-700',
    details: 'Spindle RPM: Standby',
    timeLeft: 'Slot: 14:00 - 17:00',
  },
];

export const COURSE_IMPACT_DATA: CourseImpactItem[] = [
  { code: 'CS201', title: 'Data Structures & Algorithms', degreeSem: 'B.Tech IV', examDate: 'Upcoming Mon, 09:30', cohort: '740 Students' },
  { code: 'EC304', title: 'Microcontrollers & Embedded Sys', degreeSem: 'B.Tech VI', examDate: 'Upcoming Wed, 14:00', cohort: '520 Students' },
  { code: 'ME210', title: 'Kinematics & Dynamics of Machines', degreeSem: 'B.Tech IV', examDate: 'Upcoming Fri, 09:30', cohort: '410 Students' },
  { code: 'ROB402', title: 'Autonomous Mobile Robotics', degreeSem: 'B.Tech VIII', examDate: 'Next Mon, 09:30', cohort: '290 Students' },
  { code: 'AI501', title: 'Deep Learning for Computer Vision', degreeSem: 'M.Tech II', examDate: 'Next Wed, 14:00', cohort: '185 Students' },
  { code: 'EE315', title: 'Control Systems Engineering', degreeSem: 'B.Tech VI', examDate: 'Next Fri, 09:30', cohort: '615 Students' },
  { code: 'ME480', title: 'Mechatronic System Design', degreeSem: 'B.Tech VIII', examDate: 'Next Mon, 14:00', cohort: '310 Students' },
  { code: 'CS435', title: 'Reinforcement Learning & ROS 2', degreeSem: 'B.Tech VIII', examDate: 'Next Wed, 09:30', cohort: '210 Students' },
];

export const SEARCH_ARCHIVE_MATCHES = [
  {
    id: 's-1',
    community: 'Robotics Club',
    author: 'Robotics Society',
    time: '1 day ago',
    title: 'Autonomous Robotics Competition Guidelines.pdf',
    description: 'Arena dimension specifications, lidar payload restrictions, and remote kill switch standards for TechFest.',
    upvotes: 142,
    comments: 28,
    badge: 'AI DIGEST ATTACHED',
    badgeColor: 'bg-[#FFF4EF] text-[#FF4500]',
  },
  {
    id: 's-2',
    community: 'Academic Affairs',
    author: 'Safety Officer',
    time: '3 days ago',
    title: 'Safety circular regarding high-voltage LiPo batteries in lab workspaces',
    description: 'Guidelines for mandatory flameproof battery lockers and charging station time allocations in Block 4.',
    upvotes: 89,
    comments: 14,
    badge: 'SAFETY NOTICE',
    badgeColor: 'bg-red-50 text-red-700 border border-red-200',
  },
  {
    id: 's-3',
    community: 'Coding & Algorithms',
    author: 'Technical Lead',
    time: 'Recently',
    title: 'Robotics recruitment: Hardware & Firmware tasks released',
    description: 'Detailed problem statements for embedded firmware, PID controller tuning, and PCB layout challenges.',
    upvotes: 56,
    comments: 31,
  },
  {
    id: 's-4',
    community: 'Examination Cell',
    author: 'Controller of Examinations',
    time: 'Recently',
    title: 'ROB402 Autonomous Mobile Robotics: Solved Exam Papers & Heuristics',
    description: 'Includes SLAM formulation proofs, Extended Kalman Filter numerical problems, and Path Planning heuristics.',
    upvotes: 118,
    comments: 42,
    badge: 'PAST PAPERS',
    badgeColor: 'bg-blue-100 text-blue-700',
  },
  {
    id: 's-5',
    community: 'Robotics Club',
    author: 'Prof. K. Mukherjee',
    time: 'Recently',
    title: 'Research Fellowship: Quadruped Locomotion on Uneven Terrains',
    description: 'Funded research position working on model predictive control and dynamic gait synthesis on steep obstacles.',
    upvotes: 94,
    comments: 19,
    badge: 'RESEARCH STIPEND',
    badgeColor: 'bg-green-100 text-green-800',
  },
  {
    id: 's-6',
    community: 'Robotics Club',
    author: 'Robotics Team Lead',
    time: 'Recently',
    title: 'ROS 2 Humble Workspace Setup & Gazebo Simulation Docker Image',
    description: 'Standardized multi-architecture docker configuration for campus robotics project submissions.',
    upvotes: 77,
    comments: 12,
  },
  {
    id: 's-7',
    community: 'Academic Affairs',
    author: 'Academic Registrar',
    time: 'Recently',
    title: 'Syllabus Revision: ME480 Mechatronic System Design (Current Regulations)',
    description: 'Updated credit distribution, PLC programming laboratory modules, and industry electives.',
    upvotes: 43,
    comments: 8,
    badge: 'CURRICULUM',
    badgeColor: 'bg-[#EDEFF1] text-text-secondary',
  },
  {
    id: 's-8',
    community: 'Career & Placements',
    author: 'Placement Cell',
    time: 'Recently',
    title: 'Core Engineering Placement Drive: Boston Dynamics & ABB Robotics',
    description: 'Shortlisted candidate slots for on-campus technical interviews, kinematics problem solving, and aptitude rounds.',
    upvotes: 210,
    comments: 54,
    badge: 'PLACEMENT',
    badgeColor: 'bg-green-100 text-green-800',
  },
];

export const DEMO_NOTICES: CircularNoticeItem[] = [
  {
    id: 'notice-coe-01',
    docCode: 'DOC-PID-9482-COE',
    title: 'End-Semester Examination Schedule — Comprehensive Timetable & Directives',
    source: 'Examination Cell',
    officerName: 'Dr. V. Ramanathan (Controller of Examinations)',
    category: 'TIER 1 · INSTITUTIONAL',
    documentDate: 'Published recently',
    summaryBullets: [
      'Examination Windows: B.Tech End-Semester written examinations commence on schedule across all campus blocks.',
      'Clash Resolution Window: Digital clash resolution portal locks this Friday at 23:59 IST.',
      'Hall Tickets: Now available on Academic Portal. Non-programmable calculators only.',
      'Shift Times: Morning 09:30-12:30 (reporting 09:00), Afternoon 14:00-17:00 (reporting 13:30).',
    ],
    extractedText: 'Full official circular signed by Controller of Examinations. All cohorts (B.Tech, M.Tech, Dual-Degree) are governed by standard conduct rules.',
    fileName: 'circular_endsem_schedule_latest.pdf',
    fileSize: '2.4 MB (14 Pages)',
    publishedAt: '2025-04-20T11:42:00.000Z',
    status: 'broadcasted',
    targetAudience: '4,280 Registered Students',
    channels: ['Examination Cell', 'Campus Feed', 'Push Notifications'],
  },
];

export function getDemoPosts(): PostItem[] {
  return [...ALL_CAMPUS_POSTS];
}

export function getDemoRoboticsPosts(): PostItem[] {
  return [...ROBOTICS_POSTS];
}

export function getDemoCommunities(): Community[] {
  return [...DEMO_COMMUNITIES];
}

export function getDemoNotices(): CircularNoticeItem[] {
  return [...DEMO_NOTICES];
}
